version: '3.8'
services:
  minginx:
    image: nginx
    container_name: mi-nginx
    ports:
      - "127.0.0.1:443:443"
    volumes:
      - //d/dev_ops/nginx/nginx.conf:/etc/nginx/nginx.conf
      - //d/dev_ops/nginx/cert:/etc/nginx/ssl
      - //d/dev_ops/nginx/static:/usr/share/nginx/html
    depends_on:
      - minode-app
    networks:
      minode-network:
        ipv4_address: 172.21.0.2

  minode-app:
    image: bitnami/node
    container_name: minode-app
    expose:
      - "3000"
    volumes:
      - //d/dev_ops/nginx/node-back-end:/app
    networks:
      minode-network:
        ipv4_address: 172.21.0.3
    command: bash -c "cd /app && npm i && node server.js"
networks:
  minode-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16